apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt
    cert-manager.io/issuer-kind: ClusterIssuer
  name: ingress
  namespace: cattle-fleet-system
spec:
  ingressClassName: traefik
  rules:
    - host: fleet.giebert.dev
      http:
        paths:
          - backend:
              service:
                name: gitjob
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - fleet.giebert.dev
      secretName: tls-fleet-ingress